# Stage 1: Build stage
FROM registry.vsfi.ru/library/golang:1.22.3-alpine AS build

# Set the working directory
WORKDIR /app

# Copy and download dependencies
COPY server/go.mod server/go.sum ./
RUN GOPROXY=https://go-proxy-user:fn298f0g21fwr@nexus.vsfi.ru/repository/go-mod-shisha-server go mod download -x

# Copy the source code
COPY server/ .

# Build the Go application
RUN CGO_ENABLED=0 GOOS=linux go build -o server .

# Stage 2: Final stage
FROM registry.vsfi.ru/library/alpine:3.15

# Set the working directory
WORKDIR /app

# Copy the binary from the build stage
COPY --from=build /app/server .
COPY server/.env .

# Set the timezone and install CA certificates
RUN apk --no-cache add ca-certificates tzdata

# Set the entrypoint command
ENTRYPOINT ["/app/server"]
