apiVersion: v1
kind: Secret
metadata:
  name: creds
type: Opaque
data:
  SHISHA_S3_ACCESS_KEY: {{ .Values.creds.minio.user | b64enc}}
  SHISHA_S3_SECRET_KEY: {{ .Values.creds.minio.password | b64enc}}
